### ISSUE TITLE
README.md中数据库yaml配置例子错误

### ISSUE THREAD

**Issue by chenjiacun35** [testerSunshine/aotu_ui#1]
```
# config_aotu_ui.yaml
---
db:
ip: localhost
port: 3306
table: aotu_ui
uname: root
passwd: 123456
```
应该修改为：

```
# config_aotu_ui.yaml
---
db:
  ip: localhost
  port: 3306
  table: auto_ui
  uname: root
  passwd: 123456
```
